//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Image_sort.UI.LocalResources.AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Image_sort.UI.LocalResources.AppResources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        public static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can you help me?.
        /// </summary>
        public static string CanYouHelpMe {
            get {
                return ResourceManager.GetString("CanYouHelpMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete file &quot;{filename}&quot;..
        /// </summary>
        public static string CouldNotDeleteFile {
            get {
                return ResourceManager.GetString("CouldNotDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{filename}&quot; could not be deleted. 
        ///The error code is: {errcode}.
        /// </summary>
        public static string CouldNotDeleteFileMessage {
            get {
                return ResourceManager.GetString("CouldNotDeleteFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Could not load the help file.
        /// Make sure it exists..
        /// </summary>
        public static string CouldNotLoadHelpMarkdown {
            get {
                return ResourceManager.GetString("CouldNotLoadHelpMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not rename file &quot;{file}&quot;.
        /// </summary>
        public static string CouldNotRenameFile {
            get {
                return ResourceManager.GetString("CouldNotRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new folder.
        /// </summary>
        public static string CreateNewFolder {
            get {
                return ResourceManager.GetString("CreateNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What name should the folder have?.
        /// </summary>
        public static string CreateNewFolderMessage {
            get {
                return ResourceManager.GetString("CreateNewFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Folder.
        /// </summary>
        public static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the folder {folder}? 
        ///
        ///If possible, it will be moved to the recycle bin, but if it can&apos;t (for example because it&apos;s an OneDrive folder) it will not be reversable.
        ///
        ///Note: Use Tab to cycle through the answers..
        /// </summary>
        public static string DeleteFolderConfirmation {
            get {
                return ResourceManager.GetString("DeleteFolderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteImage {
            get {
                return ResourceManager.GetString("DeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t delete.
        /// </summary>
        public static string DontDelete {
            get {
                return ResourceManager.GetString("DontDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Folder.
        /// </summary>
        public static string EnterFolder {
            get {
                return ResourceManager.GetString("EnterFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info: {message}.
        /// </summary>
        public static string ExceptionMoreInfo {
            get {
                return ResourceManager.GetString("ExceptionMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: this is an offline version. It has been last updated on {date}.
        ///---
        ///
        ///{content}.
        /// </summary>
        public static string HelpLastLoadedMarkdown {
            get {
                return ResourceManager.GetString("HelpLastLoadedMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Resolution: .
        /// </summary>
        public static string HorizontalResolution {
            get {
                return ResourceManager.GetString("HorizontalResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s important!.
        /// </summary>
        public static string ItsImportant {
            get {
                return ResourceManager.GetString("ItsImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Mode.
        /// </summary>
        public static string LightMode {
            get {
                return ResourceManager.GetString("LightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Image in File Explorer.
        /// </summary>
        public static string OpenImageInFileExplorer {
            get {
                return ResourceManager.GetString("OpenImageInFileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in browser.
        /// </summary>
        public static string OpenInBrowser {
            get {
                return ResourceManager.GetString("OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate limit exceeded..
        /// </summary>
        public static string RateLimitExceeded {
            get {
                return ResourceManager.GetString("RateLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded your GitHub rate limit. You can only update, when your rate limit is not exceeded.
        ///Please wait till {TIME} for your rate limit to reset..
        /// </summary>
        public static string RateLimitExceededMessage {
            get {
                return ResourceManager.GetString("RateLimitExceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Windows Explorer Context Menu.
        /// </summary>
        public static string ShowInExplorerContextMenu {
            get {
                return ResourceManager.GetString("ShowInExplorerContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need to know more about the system You are running Image Sort on. Can You quickly answer 3 short questions? It won&apos;t take long. We won&apos;t ask You again soon either way. This survey gives me information about which systems and operating systems (f.e. 32/64 bit) to support in the future..
        /// </summary>
        public static string SystemInfoSurveyMessage {
            get {
                return ResourceManager.GetString("SystemInfoSurveyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch-friendly Mode.
        /// </summary>
        public static string TouchFriendlyMode {
            get {
                return ResourceManager.GetString("TouchFriendlyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of Image Sort is available. Do you want to update?.
        /// </summary>
        public static string UpdateConsentQuestion {
            get {
                return ResourceManager.GetString("UpdateConsentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        /// </summary>
        public static string UpdaterErrorOccured {
            get {
                return ResourceManager.GetString("UpdaterErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        ///Message or status code:.
        /// </summary>
        public static string UpdaterErrorOccuredMessage {
            get {
                return ResourceManager.GetString("UpdaterErrorOccuredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string UpdateVersion {
            get {
                return ResourceManager.GetString("UpdateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s new in this version?.
        /// </summary>
        public static string UpdateWhatsNew {
            get {
                return ResourceManager.GetString("UpdateWhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will close all open instances of &quot;Image Sort&quot;. Please finish all tasks beforehand..
        /// </summary>
        public static string UpdateWillCloseAppMessage {
            get {
                return ResourceManager.GetString("UpdateWillCloseAppMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Accent Color.
        /// </summary>
        public static string UseNativeAccentColor {
            get {
                return ResourceManager.GetString("UseNativeAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which folder needs sorting?.
        /// </summary>
        public static string WhichFolderQuestion {
            get {
                return ResourceManager.GetString("WhichFolderQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
