image: Visual Studio 2019
configuration: Release

platform:
- x86
- x64

install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
      

build:
  project: ImageSort.UnitTests\ImageSort.UnitTests.csproj
  parallel: true

after_build:
  - ps: >-
      cd .\ImageSort.WindowsSetup\;
      gitversion /updatewixversionfile;
      msbuild /p:Configuration=Release /p:Platform=$env:PLATFORM /p:OutputPath=..\artifacts\$env:PLATFORM /p:BuildProjectReferences=false;
      cd ..;