image: Visual Studio 2019
configuration: Release

platform: Any CPU

install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - ps: >-
      cd .\ImageSort.WindowsSetup\;
      gitversion /updatewixversionfile;
      cd ..;
      

build:
  project: Image-Sort.sln
  parallel: true
  verbosity: minimal

after_build:
  - ps: >-
      cd .\ImageSort.WindowsSetup\;
      MSBuild /p:Configuration=Release /p:Platform=x64 /p:OutputPath=..\artifacts\x64 /p:BuildProjectReferences=false;
      cd ..;

artifacts:
    - path: '.\artifacts\x64\ImageSort.x64.msi'
      name: ImageSort.x64.msi
      type: File
    - path: '.\artifacts\x86\ImageSort.x86.msi'
      name: ImageSort.x86.msi
      type: File