image: Visual Studio 2019
configuration: Release
platform: Any CPU

install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  parallel: true
  verbosity: minimal
  - project: ImageSort.UnitTests\ImageSort.UnitTests.csproj
  - project: ImageSort.WPF\ImageSort.WPF.csproj
