image: Visual Studio 2019
configuration: Release

platform: Any CPU

cache:
  - 'C:\ProgramData\chocolatey\bin -> appveyor.yml'
  - 'C:\ProgramData\chocolatey\lib -> appveyor.yml'
  
environment:
  _DOTNET_VERSION: "5.0.100"

install:
  - ps: "[Net.ServicePointManager]::SecurityProtocol = 'Tls12'"
  - ps: Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile ".\.tmp\dotnet-install.ps1"
  - ps: if ((-Not (Test-Path .tmp\dotnet\dotnet.exe)) -or (((.tmp\dotnet\dotnet.exe --version) -Join '') -ne $Env:_DOTNET_VERSION)) { .tmp\dotnet-install.ps1 -Version $Env:_DOTNET_VERSION -InstallDir .tmp\dotnet } else { $Env:path = $Env:APPVEYOR_BUILD_FOLDER + "\.tmp\dotnet\dotnet.exe;" + $Env:path }
  - choco install gitversion.portable -pre -y

before_build:
  - dotnet restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: Image-Sort.sln
  parallel: true
  verbosity: minimal

after_test:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
          cd .\src\ImageSort.WindowsSetup\;
          gitversion /updatewixversionfile | Out-String;
          MSBuild /p:Configuration=Release /p:Platform=x64 /p:OutputPath=..\..\artifacts\x64 /p:BuildProjectReferences=false | Out-String;
          MSBuild /p:Configuration=Release /p:Platform=x86 /p:OutputPath=..\..\artifacts\x86 /p:BuildProjectReferences=false | Out-String;
          cd ..\..;
      }


artifacts:
  - path: '.\artifacts\**\*.msi'
    name: Image Sort Installer
    type: File

deploy:
  - provider: GitHub
    release: Image Sort v$(appveyor_build_version)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: Gka4zhwdCzAkR5hGyS988om/2MSNTP+BZDilT87BtI1jA7NYq9x0BB1cBUO3gPKa
    artifact: Image Sort Installer
    on:
      APPVEYOR_REPO_TAG: true
