image: Visual Studio 2019
configuration: Release

platform: Any CPU

cache:
  - 'C:\ProgramData\chocolatey\bin -> appveyor.yml'
  - 'C:\ProgramData\chocolatey\lib -> appveyor.yml'
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'

install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: Image-Sort.sln
  parallel: true
  verbosity: minimal

after_build:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
          cd .\ImageSort.WindowsSetup\;
          gitversion /updatewixversionfile | Out-Null;
          MSBuild /p:Configuration=Release /p:Platform=x64 /p:OutputPath=..\artifacts\x64 /p:BuildProjectReferences=false | Out-Null;
          MSBuild /p:Configuration=Release /p:Platform=x86 /p:OutputPath=..\artifacts\x86 /p:BuildProjectReferences=false | Out-Null;
          cd ..;
      }


artifacts:
  - path: '.\artifacts\**\*.msi'
    name: Image Sort Installer
    type: File

deploy:
  - provider: GitHub
    release: Image Sort v$(appveyor_build_version)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: Gka4zhwdCzAkR5hGyS988om/2MSNTP+BZDilT87BtI1jA7NYq9x0BB1cBUO3gPKa
    artifact: Image Sort Installer
    on:
      APPVEYOR_REPO_TAG: true