image: Visual Studio 2019
configuration: Release

platform:
- x86
- x64

install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - ps: >-
      cd .\ImageSort.WindowsSetup\;
      gitversion /updatewixversionfile;

build:
  project: Image-Sort.sln
  parallel: true
