image: Visual Studio 2019
configuration: Release
platform: Any CPU

install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - ps: >-
      cd .\ImageSort.WindowsSetup\;
      gitversion /updatewixversionfile;

build:
  project: Image-Sort.sln
  parallel: true
  verbosity: minimal

after_build:
  - ps: >-
      msbuild /p:Configuration=Release /p:Platform=x86 /p:OutputPath=..\artifacts\x86 /p:BuildProjectReferences=false;
      msbuild /p:Configuration=Release /p:Platform=x64 /p:OutputPath=..\artifacts\x64 /p:BuildProjectReferences=false;
