# .NET Desktop

# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'Image-Sort.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'MSIX'

steps:

- task: DownloadSecureFile@1
  name: tempCert
  displayName: 'Download temp certificate'
  inputs:
    secureFile: 'ImageSort.MSIX_TemporaryKey.pfx'
- task: DownloadSecureFile@1
  name: 
  displayName: 'Download store association'
  inputs:
    secureFile: 'Package.StoreAssociation.xml'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.WorkFolder)\_temp'
    Contents: |
      ImageSort.MSIX_TemporaryKey.pfx
      Package.StoreAssociation.xml
    TargetFolder: '$(Agent.BuildDirectory)\src\ImageSort.MSIX'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    verbosityRestore: 'Minimal'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
