use std::fs;
use std::path::Path;

#[derive(serde::Deserialize)]
struct Contributor {
    github: String,
    #[serde(rename = "preferredDisplayName")]
    preferred_display_name: String,
    link: String,
}

fn main() {
    #[cfg(target_os = "windows")]
    {
        embed_resource::compile("media-sort-gui.rc", embed_resource::NONE)
            .manifest_optional()
            .unwrap();
    }

    // Read and parse contributors.json
    let contributors_path = Path::new("../../contributors.json");
    let contributors: Vec<Contributor> = if contributors_path.exists() {
        let content = fs::read_to_string(contributors_path).unwrap();
        serde_json::from_str(&content).unwrap_or_else(|_| fallback_contributors())
    } else {
        fallback_contributors()
    };

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("contributors_codegen.rs");

    let mut code = String::from("// AUTO-GENERATED by build.rs — do not edit\n\n");
    code.push_str("#[allow(dead_code)]\n");
    code.push_str("pub struct ContributorInfo {\n");
    code.push_str("    pub github: &'static str,\n");
    code.push_str("    pub preferred_display_name: &'static str,\n");
    code.push_str("    pub link: &'static str,\n");
    code.push_str("}\n\n");

    code.push_str("pub const CONTRIBUTORS: &[ContributorInfo] = &[\n");
    for c in &contributors {
        code.push_str("    ContributorInfo {\n");
        code.push_str(&format!("        github: {:?},\n", c.github));
        code.push_str(&format!(
            "        preferred_display_name: {:?},\n",
            c.preferred_display_name
        ));
        code.push_str(&format!("        link: {:?},\n", c.link));
        code.push_str("    },\n");
    }
    code.push_str("];\n");

    fs::write(dest, code).unwrap();

    // Rerun triggers
    println!("cargo:rerun-if-changed=../../contributors.json");
    println!("cargo:rerun-if-changed=build.rs");
}

fn fallback_contributors() -> Vec<Contributor> {
    vec![Contributor {
        github: "Lolle2000la".to_string(),
        preferred_display_name: "Luca Auer".to_string(),
        link: "https://mediasort.app".to_string(),
    }]
}
