//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageSort.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageSort.Localization.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        public static string CheckForUpdatesOnStartup {
            get {
                return ResourceManager.GetString("CheckForUpdatesOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete {FileName}.
        /// </summary>
        public static string CouldNotDeleteFileExceptionMessage {
            get {
                return ResourceManager.GetString("CouldNotDeleteFileExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder (C).
        /// </summary>
        public static string CreateFolder {
            get {
                return ResourceManager.GetString("CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete (↓).
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {FileName}.
        /// </summary>
        public static string DeleteActionMessage {
            get {
                return ResourceManager.GetString("DeleteActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &quot;{Folder}&quot; does not exist..
        /// </summary>
        public static string DirectoryNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("DirectoryNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move image selection left (left arrow key).
        /// </summary>
        public static string GoLeftTooltip {
            get {
                return ResourceManager.GetString("GoLeftTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move image selection right (right arrow key).
        /// </summary>
        public static string GoRightTooltip {
            get {
                return ResourceManager.GetString("GoRightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install prerelease builds.
        /// </summary>
        public static string InstallPrereleaseBuilds {
            get {
                return ResourceManager.GetString("InstallPrereleaseBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move (↑).
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {FileName} to {Directory}.
        /// </summary>
        public static string MoveActionMessage {
            get {
                return ResourceManager.GetString("MoveActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What name should the folder have?.
        /// </summary>
        public static string NewFolderPromptText {
            get {
                return ResourceManager.GetString("NewFolderPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a folder.
        /// </summary>
        public static string NewFolderPromptTitle {
            get {
                return ResourceManager.GetString("NewFolderPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder (O).
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open selected folder (Enter).
        /// </summary>
        public static string OpenSelectedFolder {
            get {
                return ResourceManager.GetString("OpenSelectedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin (P).
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin selected (F).
        /// </summary>
        public static string PinSelected {
            get {
                return ResourceManager.GetString("PinSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo (E).
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename (R).
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename {OldFileName} to {NewFileName}.
        /// </summary>
        public static string RenameActionMessage {
            get {
                return ResourceManager.GetString("RenameActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What name to rename the image to?.
        /// </summary>
        public static string RenameImagePromptText {
            get {
                return ResourceManager.GetString("RenameImagePromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename image.
        /// </summary>
        public static string RenameImagePromptTitle {
            get {
                return ResourceManager.GetString("RenameImagePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &quot;{FileName}&quot; contains illegal characters..
        /// </summary>
        public static string RenameNewNameContainsIllegalCharacters {
            get {
                return ResourceManager.GetString("RenameNewNameContainsIllegalCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search images... (Shortcuts: I to focus, Tab to leave).
        /// </summary>
        public static string SearchTermWatermark {
            get {
                return ResourceManager.GetString("SearchTermWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo (Q).
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin (U).
        /// </summary>
        public static string Unpin {
            get {
                return ResourceManager.GetString("Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of Image Sort is available: {TagName}
        ///
        ///Do you want to update?.
        /// </summary>
        public static string UpdateAvailablePromptText {
            get {
                return ResourceManager.GetString("UpdateAvailablePromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available.
        /// </summary>
        public static string UpdateAvailablePromptTitle {
            get {
                return ResourceManager.GetString("UpdateAvailablePromptTitle", resourceCulture);
            }
        }
    }
}
