//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageSort.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KeyBindingNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyBindingNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageSort.Localization.KeyBindingNames", typeof(KeyBindingNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder below.
        /// </summary>
        public static string FolderDown {
            get {
                return ResourceManager.GetString("FolderDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse folder.
        /// </summary>
        public static string FolderLeft {
            get {
                return ResourceManager.GetString("FolderLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder management.
        /// </summary>
        public static string FolderManagementHeader {
            get {
                return ResourceManager.GetString("FolderManagementHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand folder (list sub-folders).
        /// </summary>
        public static string FolderRight {
            get {
                return ResourceManager.GetString("FolderRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder selection.
        /// </summary>
        public static string FolderSelectionHeader {
            get {
                return ResourceManager.GetString("FolderSelectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string FoldersHeader {
            get {
                return ResourceManager.GetString("FoldersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder above.
        /// </summary>
        public static string FolderUp {
            get {
                return ResourceManager.GetString("FolderUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image on the left.
        /// </summary>
        public static string GoLeft {
            get {
                return ResourceManager.GetString("GoLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image on the right.
        /// </summary>
        public static string GoRight {
            get {
                return ResourceManager.GetString("GoRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HistoryHeader {
            get {
                return ResourceManager.GetString("HistoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image management.
        /// </summary>
        public static string ImageManagementHeader {
            get {
                return ResourceManager.GetString("ImageManagementHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image selection.
        /// </summary>
        public static string ImageSelectionHeader {
            get {
                return ResourceManager.GetString("ImageSelectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string ImagesHeader {
            get {
                return ResourceManager.GetString("ImagesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string OpenFolderHeader {
            get {
                return ResourceManager.GetString("OpenFolderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned folders.
        /// </summary>
        public static string PinnedFoldersHeader {
            get {
                return ResourceManager.GetString("PinnedFoldersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search images.
        /// </summary>
        public static string SearchImagesHeader {
            get {
                return ResourceManager.GetString("SearchImagesHeader", resourceCulture);
            }
        }
    }
}
