//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageSort.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageSort.Localization.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play animated gifs.
        /// </summary>
        public static string ActivateAnimatedGifs {
            get {
                return ResourceManager.GetString("ActivateAnimatedGifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview animated gifs in thumbnails.
        /// </summary>
        public static string ActivateAnimatedGifsInThumbnails {
            get {
                return ResourceManager.GetString("ActivateAnimatedGifsInThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated Gifs.
        /// </summary>
        public static string AnimatedGifs {
            get {
                return ResourceManager.GetString("AnimatedGifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Changing settings regarding animated gifs will not affect already loaded gifs..
        /// </summary>
        public static string AnimatedGifsSettingsChangeNotice {
            get {
                return ResourceManager.GetString("AnimatedGifsSettingsChangeNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        public static string CheckForUpdatesOnStartup {
            get {
                return ResourceManager.GetString("CheckForUpdatesOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not execute action &quot;{ActMessage}&quot;:
        ///
        ///{ErrorMessage}.
        /// </summary>
        public static string CouldNotActErrorText {
            get {
                return ResourceManager.GetString("CouldNotActErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete {FileName}.
        /// </summary>
        public static string CouldNotDeleteFileExceptionMessage {
            get {
                return ResourceManager.GetString("CouldNotDeleteFileExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load &quot;{FileName}&quot;
        ///
        ///Message: {ErrorMessage}
        ///
        ///Note: Usually this is because the file is damaged.
        /// </summary>
        public static string CouldNotLoadImageErrorText {
            get {
                return ResourceManager.GetString("CouldNotLoadImageErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not redo action &quot;{ActMessage}&quot;:
        ///
        ///{ErrorMessage}.
        /// </summary>
        public static string CouldNotRedoErrorText {
            get {
                return ResourceManager.GetString("CouldNotRedoErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not undo action &quot;{ActMessage}&quot;: 
        ///
        ///{ErrorMessage}.
        /// </summary>
        public static string CouldNotUndoErrorText {
            get {
                return ResourceManager.GetString("CouldNotUndoErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        public static string CreateFolder {
            get {
                return ResourceManager.GetString("CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string CreditsLicenseLink {
            get {
                return ResourceManager.GetString("CreditsLicenseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string CreditsProjectLink {
            get {
                return ResourceManager.GetString("CreditsProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These open source projects made Image Sort possible:.
        /// </summary>
        public static string CreditsWindowLeadingText {
            get {
                return ResourceManager.GetString("CreditsWindowLeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string CreditsWindowTitle {
            get {
                return ResourceManager.GetString("CreditsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {FileName}.
        /// </summary>
        public static string DeleteActionMessage {
            get {
                return ResourceManager.GetString("DeleteActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &quot;{Directory}&quot; does not exist..
        /// </summary>
        public static string DirectoryNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("DirectoryNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t update.
        /// </summary>
        public static string DoNotUpdate {
            get {
                return ResourceManager.GetString("DoNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{FileName}&quot; already exists..
        /// </summary>
        public static string FileAlreadyExistsExceptionMessage {
            get {
                return ResourceManager.GetString("FileAlreadyExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General settings.
        /// </summary>
        public static string GeneralSettingsHeader {
            get {
                return ResourceManager.GetString("GeneralSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move image selection left (left arrow key).
        /// </summary>
        public static string GoLeftTooltip {
            get {
                return ResourceManager.GetString("GoLeftTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move image selection right (right arrow key).
        /// </summary>
        public static string GoRightTooltip {
            get {
                return ResourceManager.GetString("GoRightTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install prerelease builds.
        /// </summary>
        public static string InstallPrereleaseBuilds {
            get {
                return ResourceManager.GetString("InstallPrereleaseBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key bindings.
        /// </summary>
        public static string KeyBindingsSettingsHeader {
            get {
                return ResourceManager.GetString("KeyBindingsSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string MetadataPanelHeader {
            get {
                return ResourceManager.GetString("MetadataPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {FileName} to {Directory}.
        /// </summary>
        public static string MoveActionMessage {
            get {
                return ResourceManager.GetString("MoveActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the selected pinned folder down.
        /// </summary>
        public static string MoveSelectedPinnedFolderDown {
            get {
                return ResourceManager.GetString("MoveSelectedPinnedFolderDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the selected pinned folder up.
        /// </summary>
        public static string MoveSelectedPinnedFolderUp {
            get {
                return ResourceManager.GetString("MoveSelectedPinnedFolderUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What name should the folder have?.
        /// </summary>
        public static string NewFolderPromptText {
            get {
                return ResourceManager.GetString("NewFolderPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder.
        /// </summary>
        public static string NewFolderPromptTitle {
            get {
                return ResourceManager.GetString("NewFolderPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open selected folder.
        /// </summary>
        public static string OpenSelectedFolder {
            get {
                return ResourceManager.GetString("OpenSelectedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned folders.
        /// </summary>
        public static string PinnedFoldersSettingsHeader {
            get {
                return ResourceManager.GetString("PinnedFoldersSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin selected.
        /// </summary>
        public static string PinSelected {
            get {
                return ResourceManager.GetString("PinSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename {OldFileName} to {NewFileName}.
        /// </summary>
        public static string RenameActionMessage {
            get {
                return ResourceManager.GetString("RenameActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What name to rename the image to?.
        /// </summary>
        public static string RenameImagePromptText {
            get {
                return ResourceManager.GetString("RenameImagePromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename image.
        /// </summary>
        public static string RenameImagePromptTitle {
            get {
                return ResourceManager.GetString("RenameImagePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &quot;{FileName}&quot; contains illegal characters..
        /// </summary>
        public static string RenameNewNameContainsIllegalCharacters {
            get {
                return ResourceManager.GetString("RenameNewNameContainsIllegalCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore default key bindings.
        /// </summary>
        public static string RestoreDefaultKeyBindings {
            get {
                return ResourceManager.GetString("RestoreDefaultKeyBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search images... (press &apos;Tab&apos; to leave).
        /// </summary>
        public static string SearchTermWatermark {
            get {
                return ResourceManager.GetString("SearchTermWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin.
        /// </summary>
        public static string Unpin {
            get {
                return ResourceManager.GetString("Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of Image Sort is available: {TagName}
        ///
        ///Do you want to update?.
        /// </summary>
        public static string UpdateAvailablePromptText {
            get {
                return ResourceManager.GetString("UpdateAvailablePromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available.
        /// </summary>
        public static string UpdateAvailablePromptTitle {
            get {
                return ResourceManager.GetString("UpdateAvailablePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
    }
}
