use std::fs;
use std::path::Path;

fn main() {
    let locales_dir = Path::new("../../resources/locale");
    let mut locales: Vec<(String, String)> = Vec::new();

    if let Ok(entries) = fs::read_dir(locales_dir) {
        locales = entries
            .flatten()
            .filter_map(|entry| {
                if entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
                    let code = entry.file_name().into_string().ok()?;
                    let display =
                        locale_display_from_ftl(&locales_dir.join(&code).join("main.ftl"), &code);
                    Some((code, display))
                } else {
                    None
                }
            })
            .collect();
    }

    locales.sort_by(|a, b| a.0.cmp(&b.0));

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("locales_codegen.rs");
    let mut code = String::from("// AUTO-GENERATED by build.rs — do not edit\n\n");

    // Available locales list
    let codes: Vec<&str> = locales.iter().map(|(c, _)| c.as_str()).collect();
    code.push_str(&format!(
        "pub const AVAILABLE_LOCALES: &[&str] = &{:?};\n\n",
        codes
    ));

    // Display name mapping
    code.push_str("pub fn locale_display_name(code: &str) -> &str {\n");
    code.push_str("    match code {\n");
    for (c, d) in &locales {
        code.push_str(&format!("        \"{}\" => \"{}\",\n", c, d));
    }
    code.push_str("        _ => code,\n    }\n}\n\n");

    // FTL loader — returns None for English or unknown (caller falls back to en)
    code.push_str("pub fn load_ftl(locale: &str) -> Option<&'static str> {\n");
    code.push_str("    match locale {\n");
    for (c, _) in &locales {
        if c != "en" {
            code.push_str(&format!(
                "        \"{}\" => Some(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../resources/locale/{}/main.ftl\"))),\n",
                c, c
            ));
        }
    }
    code.push_str("        _ => None,\n    }\n}\n");

    fs::write(dest, code).unwrap();

    for (c, _) in &locales {
        println!(
            "cargo:rerun-if-changed=../../resources/locale/{}/main.ftl",
            c
        );
    }
    println!("cargo:rerun-if-changed=../../resources/locale/");
}

fn locale_display_from_ftl(ftl_path: &Path, code: &str) -> String {
    if let Ok(content) = fs::read_to_string(ftl_path) {
        for line in content.lines() {
            if let Some(name) = line.strip_prefix("# locale-name: ") {
                return name.trim().to_string();
            }
        }
    }
    code.to_string()
}
