//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Image_sort.UI.LocalResources.ToolTips {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToolTips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolTips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Image_sort.UI.LocalResources.ToolTips.ToolTips", typeof(ToolTips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the current image to the recycle bin.
        ///
        ///Note: This cannot be reverted in-app. You must revert an deletion from inside the recycle bin yourself..
        /// </summary>
        public static string DeleteImageTip {
            get {
                return ResourceManager.GetString("DeleteImageTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the folder selected.
        ///
        ///Shortcut: Enter.
        /// </summary>
        public static string EnterFolderToolTip {
            get {
                return ResourceManager.GetString("EnterFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Feedback page in the web browser.
        ///Your feedback will be heard!.
        /// </summary>
        public static string FeedbackToolTip {
            get {
                return ResourceManager.GetString("FeedbackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the name of the current image. You can rename image by clicking the text, editing it and then pressing enter.
        ///If you accidentally clicked on the box and don&apos;t want to rename the file, just don&apos;t change anything and press enter.
        ///
        ///Shortcut: ctrl + r.
        /// </summary>
        public static string FileNameAndRenameTip {
            get {
                return ResourceManager.GetString("FileNameAndRenameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Github account is required to file an issue.
        /// </summary>
        public static string GitHubAccountRequired {
            get {
                return ResourceManager.GetString("GitHubAccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goes back one image you skipped, if possible. 
        ///
        ///Shortcut: ctrl + left arrow key.
        /// </summary>
        public static string GoBackToolTip {
            get {
                return ResourceManager.GetString("GoBackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressing this button will launch the windows store review page. Due to incompatibilities, feedback hub currently cannot be used for giving feedback. You have to give feedback through a review and update the review, when there was an improvement..
        /// </summary>
        public static string LaunchesWindowsStore {
            get {
                return ResourceManager.GetString("LaunchesWindowsStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the image to the selected folder. 
        ///
        ///Shortcut: right arrow key.
        /// </summary>
        public static string MoveToolTip {
            get {
                return ResourceManager.GetString("MoveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new folder inside the current one.
        ///
        ///Shortcut: F3.
        /// </summary>
        public static string NewFolderToolTip {
            get {
                return ResourceManager.GetString("NewFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the currently selected image in file explorer.
        ///
        ///Shortcut: F5.
        /// </summary>
        public static string OpenImageInExplorerToolTip {
            get {
                return ResourceManager.GetString("OpenImageInExplorerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the currently selected image..
        /// </summary>
        public static string ProgressSliderToolTip {
            get {
                return ResourceManager.GetString("ProgressSliderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives you the option to change the horizontal resolution, that the images should get loaded with.
        ///
        ///Shortcut: F4.
        /// </summary>
        public static string ResolutionBoxToolTip {
            get {
                return ResourceManager.GetString("ResolutionBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows and hides the search box.
        ///
        ///Shortcut: ctrl+s.
        /// </summary>
        public static string SearchToolTip {
            get {
                return ResourceManager.GetString("SearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the folder to sort.
        ///
        ///Shortcut: F2.
        /// </summary>
        public static string SelectFolderToolTip {
            get {
                return ResourceManager.GetString("SelectFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skips the current image.
        ///
        ///Shortcut: left arrow key.
        /// </summary>
        public static string SkipToolTip {
            get {
                return ResourceManager.GetString("SkipToolTip", resourceCulture);
            }
        }
    }
}
