theme: jekyll-theme-slate
title: Image sort - a free app for sorting your folders
description: Image sort helps you sort your big and messy folders. It's tiny too, just about 3 megabytes. <a href='//www.microsoft.com/store/apps/9PGDK9WN8HG6?ocid=badge'><img src='https://assets.windowsphone.com/85864462-9c82-451e-9355-a3d5f874397a/English_get-it-from-MS_InvariantCulture_Default.png' alt='English badge' width="200"/></a>
social_image_path:  https://github.com/Lolle2000la/Image-Sort/blob/master/Image%20sort.UI/Image_Sort.png
social_logo_path:   https://github.com/Lolle2000la/Image-Sort/blob/master/Image%20sort.UI/Image_Sort.png
