theme: jekyll-theme-slate
title: Image Sort - a free app for sorting your folders
description: Image Sort helps you sort your big and messy folders with speed, not friction.
social_image_path: https://github.com/Lolle2000la/Image-Sort/blob/master/Image%20sort.UI/Image_Sort.png
social_logo_path: https://github.com/Lolle2000la/Image-Sort/blob/master/Image%20sort.UI/Image_Sort.png
