name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - labeled

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enable auto-merge for Dependabot PRs
        if: github.actor == 'dependabot[bot]' && github.event.pull_request.labels.*.name == 'dependencies'
        run: |
          PR_NUMBER=$(echo ${{ github.event.pull_request.number }})
          echo "Enabling auto-merge for PR #$PR_NUMBER"
          gh pr merge $PR_NUMBER --auto --squash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
